"""
Mapping data for Bezugszeilenart (BZArt) codes and their descriptions in different languages.
This data is used to match line items to their correct BZArt codes.
"""

BZ_MAPPING = [
    {
        "bz_art": "Anz_U",
        "description_de": "Übertrag / Vortrag",
        "description_fr": "Report",
        "description_it": "Riporto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Akonto",
        "description_de": "Akontozahlung",
        "description_fr": "Acompte",
        "description_it": "Pagamento acconto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "AkontoV",
        "description_de": "Akonto-Zahlung vor Primeo-Vertrag",
        "description_fr": "Paiement d'acompte avant contract avec Primeo",
        "description_it": "Pagamento acconto prima del contratto Primeo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "ALVST",
        "description_de": "Ausländische Vorsteuer",
        "description_fr": "Taxe étrangers",
        "description_it": "Imposta a monte estere",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Anz_Rab",
        "description_de": "Rabatt",
        "description_fr": "Rabais",
        "description_it": "Ribasso",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Clearinggebühr",
        "description_de": "Clearinggebühr Swissgrid",
        "description_fr": "Taxe de clearing Swissgrid",
        "description_it": "Tassa clearing",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "CO2_Erdgas",
        "description_de": "CO2 Abgabe auf Erdgas",
        "description_fr": "Taxe CO2 gaz naturel",
        "description_it": "CO2 tassa federale sul gas",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "CO2_FW",
        "description_de": "CO2 Abgabe auf Fernwärme",
        "description_fr": "Taxe CO2 chauffage urbain",
        "description_it": "CO2 tassa federale sul teleriscaldamento",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "CO2_KG",
        "description_de": "CO2 Abgabe auf Gewicht",
        "description_fr": "Taxe CO2 par poids",
        "description_it": "CO2 tassa federale per peso",
        "price_unit": "CHF/kg",
        "type": "Energie",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "CO2_Oel",
        "description_de": "CO2 Abgabe auf Oel",
        "description_fr": "Taxe CO2 mazout",
        "description_it": "CO2 tassa federale sul olio",
        "price_unit": "CHF/l",
        "type": "Energie",
        "unit_quantity": "l",
    },
    {
        "bz_art": "DL_Akonto_L",
        "description_de": "Akontozahlung",
        "description_fr": "Acompte",
        "description_it": "Pagamento acconto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "DL_Akonto_LV",
        "description_de": "Akontozahlung Leistung",
        "description_fr": "Acompte puissance",
        "description_it": "Pagamento acconto potenza",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "DL_BHT",
        "description_de": "Blind HT",
        "description_fr": "Réactive HP",
        "description_it": "Reatt.diurna",
        "price_unit": "CHF/kVArh",
        "type": "NULL",
        "unit_quantity": "kVArh",
    },
    {
        "bz_art": "DL_BNT",
        "description_de": "Blind NT",
        "description_fr": "Réactive HC",
        "description_it": "Reatt.nott.",
        "price_unit": "CHF/kVArh",
        "type": "NULL",
        "unit_quantity": "kVArh",
    },
    {
        "bz_art": "DL_Geb",
        "description_de": "Netz Gebühren",
        "description_fr": "Prix de base",
        "description_it": "Tassa base",
        "price_unit": "CHF",
        "type": "Netznutzung",
        "unit_quantity": "",
    },
    {
        "bz_art": "DL_HT",
        "description_de": "Netz HT",
        "description_fr": "Réseau HP",
        "description_it": "Rete.diurna",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "DL_Leistung",
        "description_de": "Netz Leistung",
        "description_fr": "Puissance",
        "description_it": "Potenza rete",
        "price_unit": "CHF/kW",
        "type": "Netznutzung",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "DL_Netzverlust_HT",
        "description_de": "DL_Netzverlust HT",
        "description_fr": "Perte de réseau HP",
        "description_it": "Perdita rete diurna",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "DL_Netzverlust_L",
        "description_de": "DL_Netzverlust  Leistung",
        "description_fr": "Perte de réseau puissance",
        "description_it": "Perdita rete potenza",
        "price_unit": "CHF/kW",
        "type": "NULL",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "DL_Netzverlust_NT",
        "description_de": "DL_Netzverlust NT",
        "description_fr": "Perte de puissance HC",
        "description_it": "Perdita rete notturna",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "DL_NT",
        "description_de": "Netz NT",
        "description_fr": "Réseau HC",
        "description_it": "Rete.notturna",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "DL_P",
        "description_de": "Durchleitung Pauschale",
        "description_fr": "Forfait réseau",
        "description_it": "Transito, forfettario",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "DL_Rabatt",
        "description_de": "Rabatt Netznutzung",
        "description_fr": "Rabais sur le réseau",
        "description_it": "Ribasso utilizzo rete",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EC",
        "description_de": "Contracting",
        "description_fr": "Contracting",
        "description_it": "Contracting",
        "price_unit": "CHF/kWh.",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EDM",
        "description_de": "Betrieb & Instandhaltung TS",
        "description_fr": "Operation & maintenance",
        "description_it": "Manutenzione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EffBonus",
        "description_de": "Effizienzbonus",
        "description_fr": "Bonus d'efficacité",
        "description_it": "Bonus efficienza",
        "price_unit": "CHF",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "EinspVerguetung_HT",
        "description_de": "Einspeisevergütung HT",
        "description_fr": "Tarifs de rachat HP",
        "description_it": "Spese per fornitura di energia diurna",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "EinspVerguetung_NT",
        "description_de": "Einspeisevergütung NT",
        "description_fr": "Tarifs de rachat HC",
        "description_it": "Spese per fornitura di energia notturna",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Entnahmeleistung",
        "description_de": "Entnahmeleistung",
        "description_fr": "Puissance d'extraction",
        "description_it": "Entnahmeleistung_it",
        "price_unit": "CHF/l",
        "type": "Energie",
        "unit_quantity": "l",
    },
    {
        "bz_art": "Entwässerung",
        "description_de": "Entwässerung/Meteorwasser",
        "description_fr": "Assainissement",
        "description_it": "Prosciugamento/drenaggio",
        "price_unit": "CHF",
        "type": "Energie",
        "unit_quantity": "",
    },
    {
        "bz_art": "EPK",
        "description_de": "Energie Preis Korrektur",
        "description_fr": "Correction prix énergie",
        "description_it": "Correzione prezzo energia",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EPK_DL",
        "description_de": "Durchleitungspreis Korrektur",
        "description_fr": "Correction prix réseau",
        "description_it": "Correzione prezzo transito rete",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EPK_DL_Leistung",
        "description_de": "Preiskorrektur Netz Leistung",
        "description_fr": "Correction prix puissance du réseau",
        "description_it": "Correzione prezzo potenza rete",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EPK_Leistung",
        "description_de": "Preiskorrektur Leistung",
        "description_fr": "Correction prix réseau",
        "description_it": "Correzione prezzo potenza",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "EPK_SA",
        "description_de": "Korrektur Steuern&Abgaben",
        "description_fr": "Correction redevances communales",
        "description_it": "Correzione contributi ai comuni",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "ERA_M",
        "description_de": "Energiereserve",
        "description_fr": "Réserve d'énergie",
        "description_it": "Riserva di energia",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "ERA_M",
        "description_de": "Energiereserve",
        "description_fr": "Réserve d'énergie",
        "description_it": "Riserva di energia",
        "price_unit": "CHF/kWh",
        "type": "Rest",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Erdgas_Geb",
        "description_de": "Erdgas Gebühren",
        "description_fr": "Taxe base gaz naturel",
        "description_it": "Componente base gas",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Erdgas_kWh",
        "description_de": "Erdgas kWh",
        "description_fr": "Gaz naturel kWh",
        "description_it": "Consumo gas",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "ERg",
        "description_de": "Rabatt Elektronische Datenübermittlung",
        "description_fr": "Rabais pour transmission des données électronique",
        "description_it": "Sconto per trasmissione dei dati elettronici",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "FK_Geb",
        "description_de": "Fernkälte Gebühren",
        "description_fr": "Tasse base refroidissement urbain",
        "description_it": "Tassa refrigerazione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "FK_kWh",
        "description_de": "Fernkälte kWh",
        "description_fr": "Refroidissement urbain kWh",
        "description_it": "Refrigerazione kWh",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "FW_Geb",
        "description_de": "Fernwärme Gebühren",
        "description_fr": "Tasse base chauffage urbain",
        "description_it": "Tassa teleriscaldamento",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "FW_kWh",
        "description_de": "Fernwärme kWh",
        "description_fr": "Chauffage urbain kWh",
        "description_it": "Teleriscaldamento kWh",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Geb",
        "description_de": "Gebühr Allg.",
        "description_fr": "Prix de base",
        "description_it": "Tassa generale",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_E",
        "description_de": "Einmalgebühren",
        "description_fr": "Taxe unique",
        "description_it": "Tassa unica",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_FA",
        "description_de": "Förderabgabe BS",
        "description_fr": "Taxe d'incitation ER",
        "description_it": "Incentivo energia rinnovabile",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_G",
        "description_de": "Grundgebühr",
        "description_fr": "Taxe de base",
        "description_it": "Tassa base",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_KZ",
        "description_de": "Konzessionsgebühr",
        "description_fr": "Taxe concession",
        "description_it": "Tassa di concessione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_KZM",
        "description_de": "Konzessionsgebühr",
        "description_fr": "Taxe concession",
        "description_it": "Tassa di concessione",
        "price_unit": "CHF",
        "type": "Netznutzung",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_KZR",
        "description_de": "Konzessionsrabatt",
        "description_fr": "Rabais concession",
        "description_it": "Sconto concessione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_LA",
        "description_de": "Lenkungsabgabe BS",
        "description_fr": "Fond d'incitation ER",
        "description_it": "Incentivo fondo risparmio energetico",
        "price_unit": "CHF",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Geb_M",
        "description_de": "Mahngebühren",
        "description_fr": "Amendes de retard",
        "description_it": "Spese di sollecito",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_Mob_Srv",
        "description_de": "Mobilitätsdienstleistung",
        "description_fr": "Mobilitätsdienstleistung",
        "description_it": "Mobilitätsdienstleistung",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_MV",
        "description_de": "Mahngebühren verrechenbar",
        "description_fr": "Amendes de retard à mettre en compte",
        "description_it": "Spese di sollecito da mettere in conto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_NKU",
        "description_de": "Gebühr (NK-unfähig)",
        "description_fr": "Gebühr (NK-unfähig)_fr",
        "description_it": "Gebühr (NK-unfähig)_it",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_TBAK",
        "description_de": "Gebühren BAKOM",
        "description_fr": "Gebühren BAKOM",
        "description_it": "Gebühren BAKOM",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_TK",
        "description_de": "Gebühren Telekommunikation",
        "description_fr": "Taxe télécommunications",
        "description_it": "Tassa telecomunicazione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_TNet",
        "description_de": "Gebühren Internet",
        "description_fr": "Gebühren Internet",
        "description_it": "Gebühren Internet",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_TT",
        "description_de": "Gebühren Telefon",
        "description_fr": "Gebühren Telefon",
        "description_it": "Gebühren Telefon",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_TV",
        "description_de": "Gebühren Cable/TV",
        "description_fr": "Gebühren Cable/TV",
        "description_it": "Gebühren Cable/TV",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_W",
        "description_de": "Gebühr Wasser",
        "description_fr": "Taxe eau",
        "description_it": "Tassa acqua",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_Z",
        "description_de": "Zählermiete",
        "description_fr": "Taxe location du compteur",
        "description_it": "Tassa contatore",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Geb_ZFA",
        "description_de": "Gebühr für Zählerfernauslesung",
        "description_fr": "Taxe télérelève",
        "description_it": "Tassa per telelettura",
        "price_unit": "CHF",
        "type": "Netznutzung",
        "unit_quantity": "",
    },
    {
        "bz_art": "HT",
        "description_de": "Energie HT",
        "description_fr": "Énergie HP",
        "description_it": "Ener.diurna",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Kehricht kg",
        "description_de": "Kehricht kg",
        "description_fr": "Déchets kg",
        "description_it": "Rifiuti kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "Kehricht L",
        "description_de": "Kehricht Liter",
        "description_fr": "Déchets litre",
        "description_it": "Rifiuti litri",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "l",
    },
    {
        "bz_art": "KEV",
        "description_de": "KEV",
        "description_fr": "Taxe d'encouragement légale",
        "description_it": "Contributo federale energie rinnovabili",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KEVV_BE",
        "description_de": "KEV Bew.-Entgelt DV",
        "description_fr": "Rétribution de l'energie produite (RPC)",
        "description_it": "Retribuzione energie prodotta (RPC)",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KEVV_BEA",
        "description_de": "KEV Anteil Bew.-Entgelt DV",
        "description_fr": "KEV Bew.-Entgelt DV",
        "description_it": "KEV Bew.-Entgelt DV",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KEVV_EP",
        "description_de": "KEV Einspeiseprämie",
        "description_fr": "Rétribution de l'energie produite (RPC)",
        "description_it": "Retribuzione energie prodotta (RPC)",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KEVV_RM",
        "description_de": "KEV Vergütung Ref.marktpreis",
        "description_fr": "Rétribution de l'energie produite (RPC)",
        "description_it": "Retribuzione energie prodotta (RPC)",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KLeistung",
        "description_de": "Kontrollzähler (Leistung)",
        "description_fr": "Compteur de controlle (puissance)",
        "description_it": "Contatore controllo (potenza)",
        "price_unit": "CHF.",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "KZBH",
        "description_de": "Kontrollz. BHT",
        "description_fr": "Compteur de controlle réactiv HP",
        "description_it": "Contatore controllo, reattiva diurna",
        "price_unit": "CHF/kVArh",
        "type": "NULL",
        "unit_quantity": "kVArh",
    },
    {
        "bz_art": "KZBN",
        "description_de": "Kontrollz BNT",
        "description_fr": "Compteur de controlle energie réactiv bas",
        "description_it": "Contatore controllo, reattiva notturna",
        "price_unit": "CHF/kVArh",
        "type": "NULL",
        "unit_quantity": "kVArh",
    },
    {
        "bz_art": "KZH",
        "description_de": "Kontrollz. HT",
        "description_fr": "Compteur de controlle energie HP",
        "description_it": "Contatore controllo diurna",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "KZLH",
        "description_de": "Kontrollz. Leist.",
        "description_fr": "Compteur de controlle puissance",
        "description_it": "Contatore controllo potenza",
        "price_unit": "CHF.",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "KZLN",
        "description_de": "Kontrollz. Leist",
        "description_fr": "Compteur de controlle puissance",
        "description_it": "Contatore controllo potenza",
        "price_unit": "CHF.",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "KZN",
        "description_de": "Kontrollz. NT",
        "description_fr": "Compteur de controlle energie bas",
        "description_it": "Contatore controllo notturna",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Leistung",
        "description_de": "Leistung",
        "description_fr": "Puissance",
        "description_it": "Potenza",
        "price_unit": "CHF/kW",
        "type": "Energie",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "LHT",
        "description_de": "Leistung HT",
        "description_fr": "Puissance HP",
        "description_it": "Potenza diurna",
        "price_unit": "CHF/kW",
        "type": "NULL",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "LNT",
        "description_de": "Leistung NT",
        "description_fr": "Puissance HC",
        "description_it": "Potenza notturna",
        "price_unit": "CHF/kW",
        "type": "NULL",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "Material_K",
        "description_de": "Materialkosten",
        "description_fr": "Coût des matières",
        "description_it": "Costi materiale",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "MessungFuellstandL",
        "description_de": "Messung Füllstand L",
        "description_fr": "Mensuration kWh",
        "description_it": "Rilevamento kWh",
        "price_unit": "CHF/L",
        "type": "Energie",
        "unit_quantity": "",
    },
    {
        "bz_art": "MessungkWh",
        "description_de": "Messung kWh",
        "description_fr": "Mensuration kWh",
        "description_it": "Rilevamento kWh",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "MessungkWh_HT",
        "description_de": "Messung HT",
        "description_fr": "Mensuration HP",
        "description_it": "Rilevamento diurna",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "MessungkWh_NT",
        "description_de": "Messung NT",
        "description_fr": "Mensuration HC",
        "description_it": "Rilevamento nott.",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Minimal_DLK",
        "description_de": "Minimalbetrag Durchleitunskosten",
        "description_fr": "Coût minimal réseau",
        "description_it": "Importo minimo rete",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Minimal_EK",
        "description_de": "Minimalbetrag Energiekosten",
        "description_fr": "Coût minimal énergie",
        "description_it": "Importo minimo energia",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "MWST_EUR",
        "description_de": "MWST Billing EUR",
        "description_fr": "TVA Billing EUR",
        "description_it": "IVA Billing EUR",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "NDL_HT",
        "description_de": "Nationale Durchleitung HT",
        "description_fr": "Réseau national HP",
        "description_it": "Transito energia nazionale diurna",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "NDL_Leistung",
        "description_de": "Nationale Durchleitung Leistung",
        "description_fr": "Réseau national puissance",
        "description_it": "Transito energia nazionale potenza",
        "price_unit": "CHF/kW",
        "type": "NULL",
        "unit_quantity": "kW",
    },
    {
        "bz_art": "NDL_NT",
        "description_de": "Nationale Durchleitung NT",
        "description_fr": "Réseau national HC",
        "description_it": "Transito energia nazionale notturna",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "NDL_System",
        "description_de": "Systemdienstleistungen",
        "description_fr": "Services-système Swissgrid",
        "description_it": "Prestazioni di sistema generale Swissgrid",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "NT",
        "description_de": "Energie NT",
        "description_fr": "Énergie HC",
        "description_it": "Ener.notturna",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "P",
        "description_de": "Pauschale (verr.bar)",
        "description_fr": "Forfait",
        "description_it": "Forfettario",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "P_Mehrfach",
        "description_de": "Pauschale mehrfach (verr.bar)",
        "description_fr": "Plusieurs forfait",
        "description_it": "Forfettario multiplo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Pellets",
        "description_de": "Pellets",
        "description_fr": "Pellets",
        "description_it": "Pellet",
        "price_unit": "CHF/kg",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "PPV_ET",
        "description_de": "Lokale Eigenproduktion",
        "description_fr": "Énergie locale",
        "description_it": "Energia locale",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Propangas_kg",
        "description_de": "Propangas kg",
        "description_fr": "Propane kg",
        "description_it": "Propano kg",
        "price_unit": "CHF/kg",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "Rab_Einm",
        "description_de": "Einmal-Rabatt",
        "description_fr": "Rabais unique",
        "description_it": "Riduzione unica",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "RabattMenge",
        "description_de": "Rabatt auf Menge",
        "description_fr": "Rabais",
        "description_it": "Ribasso",
        "price_unit": "CHF",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "rGeb",
        "description_de": "Recycling Gebühren Stück",
        "description_fr": "Frais de recyclage Pièce",
        "description_it": "Tassa di riciclaggio pezzo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "Stück",
    },
    {
        "bz_art": "rkg Bauschutt gemischt / Inertstoff",
        "description_de": "Recycling Bauschutt gemischt Typ B",
        "description_fr": "déchets de construction mélangés de type B",
        "description_it": "Riciclaggio di rifiuti edili misti di tipo B",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkg130208S Altöl",
        "description_de": "Recycling 130208S Altöl",
        "description_fr": "Recyclage 130208S Huile usagée",
        "description_it": "Riciclaggio 130208S Olio esausto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkg160209S Kondensatoren PCB-haltig",
        "description_de": "Recycling 160209S Kondensatoren PCB-haltig",
        "description_fr": "Recyclage 160209S Condensateurs contenant des PCB",
        "description_it": "Riciclaggio di condensatori 160209S contenenti PCB",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkg160209S Kondensatoren PCB-haltig_2",
        "description_de": "Recycling 160209S Kondensatoren PCB-haltig",
        "description_fr": "Recyclage 160209S Condensateurs contenant des PCB",
        "description_it": "Riciclaggio di condensatori 160209S contenenti PCB",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAbfall brennbar",
        "description_de": "Recycling Abfall brennbar",
        "description_fr": "Recyclage Déchets combustibles",
        "description_it": "Riciclaggio di rifiuti combustibili",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminium",
        "description_de": "Recycling Aluminium kg",
        "description_fr": "Recyclage de l'aluminium kg",
        "description_it": "Riciclaggio dell'alluminio kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminium Getränkedosen",
        "description_de": "Recycling Aluminium Getränkedosen",
        "description_fr": "Recyclage de l'aluminium Boîtes de boisson",
        "description_it": "Riciclaggio di lattine per bevande in alluminio",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminium/Kupfer Kabel",
        "description_de": "Recycling Aluminium/Kupfer Kabel",
        "description_fr": "Recyclage aluminium/cuivre Câbles",
        "description_it": "Riciclaggio di cavi in alluminio/rame",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminiumkabel",
        "description_de": "Recycling Aluminiumkabel",
        "description_fr": "Recyclage des câbles en aluminium",
        "description_it": "Riciclaggio dei cavi di alluminio",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminiumschrott",
        "description_de": "Recycling Aluminiumschrott",
        "description_fr": "Recyclage de la ferraille d'aluminium",
        "description_it": "Riciclaggio dei cavi di alluminio",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgAluminiumtrennmaterial 15% Tol",
        "description_de": "Recycling Aluminiumtrennmaterial 15% Tol",
        "description_fr": "Matériau de séparation en aluminium 15% Tol",
        "description_it": "Materiale di separazione in alluminio 15% Tol",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBauschutt",
        "description_de": "Recycling Bauschutt",
        "description_fr": "Recyclage des gravats",
        "description_it": "Riciclaggio di rifiuti da costruzione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBauschutt sauber (Typ A)",
        "description_de": "Recycling Bauschutt sauber Typ A",
        "description_fr": "Recyclage des gravats propres de type A",
        "description_it": "Riciclaggio di rifiuti edili puliti di tipo A",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBausperrgut",
        "description_de": "Recycling Bausperrgut",
        "description_fr": "Recyclage des déchets de construction encombrants",
        "description_it": "Riciclaggio dei rifiuti edili",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBetonabbruch",
        "description_de": "Recycling Betonabbruch",
        "description_fr": "Recyclage Démolition du béton",
        "description_it": "Riciclaggio Demolizione del calcestruzzo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBlech",
        "description_de": "Recycling Blech",
        "description_fr": "Recyclage tôle",
        "description_it": "Riciclaggio lamiera",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBlei",
        "description_de": "Recycling Bei",
        "description_fr": "Recyclage Plomb",
        "description_it": "Riciclaggio Piombo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgBleibatterien",
        "description_de": "Recycling Bleibatterien",
        "description_fr": "Recyclage des batteries au plomb",
        "description_it": "Riciclaggio di batterie al piombo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgEisen",
        "description_de": "Recycling Eisen kg",
        "description_fr": "Recyclage du fer kg",
        "description_it": "Riciclaggio del ferro kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgEntsorgungsgueter",
        "description_de": "Recycling Entsorgungsgüter kg",
        "description_fr": "Recyclage des déchets kg",
        "description_it": "Riciclaggio Smaltimento merci kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgEternit",
        "description_de": "Recycling Eternit",
        "description_fr": "Recyclage eternit",
        "description_it": "Riciclaggio eternit",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgFolien",
        "description_de": "Recycling Folien kg",
        "description_fr": "Films recyclés kg",
        "description_it": "Fogli di riciclo kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgGlas",
        "description_de": "Recycling Glas",
        "description_fr": "Recyclage du verre",
        "description_it": "Riciclaggio del vetro",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgHolz",
        "description_de": "Recycling Holz kg",
        "description_fr": "Bois recyclé kg",
        "description_it": "Riciclaggio del legno kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgHolz Klasse 2-3",
        "description_de": "Recycling Holz Klasse 2-3",
        "description_fr": "Recyclage bois classe 2-3",
        "description_it": "Riciclaggio di legno classe 2-3",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgHolz Klasse 4",
        "description_de": "Recycling Holz Klasse 4 / Kontaminiert",
        "description_fr": "Recyclage Bois classe 4 / Contaminés",
        "description_it": "Riciclaggio di legno di classe 4 / contaminato",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgIndustrie Abfall",
        "description_de": "Recycling Industrie und Gewerbe Abfall",
        "description_fr": "Recyclage des déchets industriels et commerciaux",
        "description_it": "Riciclaggio di rifiuti industriali e commerciali",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgIndustrieelekronik",
        "description_de": "Recycling Industrieelekronik",
        "description_fr": "Recyclage de l'électronique industrielle",
        "description_it": "Riciclaggio dell'elettronica industriale",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgIsocyanatabfälle",
        "description_de": "Recycling Isocyanatabfälle",
        "description_fr": "Recyclage des déchets d'isocyanate",
        "description_it": "Riciclaggio dei rifiuti di isocianato",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKabelschälblei",
        "description_de": "Recycling Kabelschälblei",
        "description_fr": "Recyclage du plomb de pelage des câbles",
        "description_it": "Riciclaggio dei rottami di alluminio",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKarton",
        "description_de": "Recycling Karton kg",
        "description_fr": "Carton recyclé kg",
        "description_it": "Riciclaggio del cartone kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKeramik",
        "description_de": "Recycling Keramik kg",
        "description_fr": "Céramique recyclée kg",
        "description_it": "Riciclaggio della ceramica kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKompressoren Kühlgeräte",
        "description_de": "Recycling Kompressoren Kühlgeräte",
        "description_fr": "Compresseurs Appareils de réfrigération",
        "description_it": "Compressori Frigoriferi",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKondensatoren PCB frei mit Oel",
        "description_de": "Kondensatoren PCB frei mit Oel",
        "description_fr": "Condensateurs sans PCB avec huile",
        "description_it": "Condensatori senza PCB con olio",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKunststoffe",
        "description_de": "Recycling Gewicht",
        "description_fr": "Recycling Poids",
        "description_it": "Recycling Peso",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupfer ECU",
        "description_de": "Recycling Kupfer",
        "description_fr": "Recyclage cuivre ou plomb",
        "description_it": "Riciclaggio di piombo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": 'rkgKupfer"Millberry"',
        "description_de": "Recycling Kupfer",
        "description_fr": "Recyclage cuivre ou plomb",
        "description_it": "Riciclaggio di piombo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferBleiErdkabel",
        "description_de": "Recycling Kupfer oder Blei Erdkabel",
        "description_fr": "Recyclage cuivre ou plomb Câble de terre",
        "description_it": "Riciclaggio di cavi con buccia di piombo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupfererdkabel Fe/Pb-armiert",
        "description_de": "Recycling Kupfererdkabel Fe/Pb-armiert",
        "description_fr": "Recyclage câble de terre en cuivre armé Fe/Pb",
        "description_it": "Riciclaggio cavo di terra in rame armato Fe/Pb",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel isoliert 38% Cu",
        "description_de": "Kupferkabel isoliert 38% Cu",
        "description_fr": "Câble en cuivre isolé 38% Cu",
        "description_it": "Cavo in rame isolato al 38% Cu",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel isoliert Ein-/Mehrleiter, 63% Cu",
        "description_de": "Kupferkabel isoliert Ein-/Mehrleiter, 63% Cu",
        "description_fr": "câble cuivre isolé mono/mono conducteur, 63% Cu",
        "description_it": "Cavo di rame riciclato isolato 63% CU",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel isoliert Einleiter 75% Cu",
        "description_de": "Kupferkabel isoliert Einleiter 75% Cu",
        "description_fr": "Câble en cuivre isolé monoconducteur 75% Cu",
        "description_it": "Cavo in rame isolato a conduttore singolo 75% Cu",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel30",
        "description_de": "Recycling Kupferkabel 30% CU",
        "description_fr": "Câble en cuivre recyclé 30% CU",
        "description_it": "Cavo di rame riciclato 30% CU",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel45",
        "description_de": "Recycling Kupferkabel 45% CU",
        "description_fr": "Câble en cuivre recyclé 45% CU",
        "description_it": "Cavo di rame riciclato 45% CU",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferkabel63",
        "description_de": "Recycling Kupferkabel 63% CU",
        "description_fr": "Câble en cuivre recyclé 63% CU",
        "description_it": "Cavo di rame riciclato 63% CU",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupfer-Litzendraht",
        "description_de": "Recycling Kupfer-Litzendraht",
        "description_fr": "Fil de cuivre toronné",
        "description_it": "Filo di rame a trefoli",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupferOberleitungsdraht",
        "description_de": "Recycling Kupfer Oberleitungsdraht",
        "description_fr": "Cuivre recyclé Fil caténaire",
        "description_it": "Cavo catenaria in rame riciclato",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgKupfer-Raffiniermaterial80",
        "description_de": "Recycling Kupfer-Raffiniermaterial 80-90% CU",
        "description_fr": "matériel de raffinage du cuivre 80-90% CU",
        "description_it": "raffinazione del rame riciclato 80-90% CU",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgLangschrott, nicht scherbar",
        "description_de": "Recycling Langschrott",
        "description_fr": "Recyclage Ferraille longue",
        "description_it": "Riciclaggio Scarto lungo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgLangschrott, scherbar",
        "description_de": "Recycling Langschrott, scherbar",
        "description_fr": "Recyclage Ferraille longue, cisaillable",
        "description_it": "Riciclaggio Scarto lungo, tranciabile",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgLeergut",
        "description_de": "Leergut",
        "description_fr": "Emballages vides",
        "description_it": "Vuoti",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgLeichteisen / Shreddervormaterial",
        "description_de": "Recycling Leichteisen / Shreddervormaterial",
        "description_fr": "Recyclage des fers légers / matériaux de broyage",
        "description_it": "Riciclaggio di ferro leggero",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgLeutmittel",
        "description_de": "Recycling Leutmittel",
        "description_fr": "Recyclage du matériel de lumiere",
        "description_it": "Riciclaggio dei residui di lavorazione",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgMuffen",
        "description_de": "Recycling Muffen",
        "description_fr": "Recyclage des manchons",
        "description_it": "Riciclaggio Maniche di riciclo",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgOrganisches Material / Grüngut",
        "description_de": "Organisches Material / Grüngut",
        "description_fr": "Matière organique / déchets verts",
        "description_it": "Materiale organico / rifiuti verdi",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgPapier",
        "description_de": "Recycling Papier kg",
        "description_fr": "Papier recyclé kg",
        "description_it": "Riciclaggio della carta kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgPET",
        "description_de": "Recycling PET",
        "description_fr": "Recyclage du PET",
        "description_it": "Riciclaggio del PET",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgPneu PKW ohne Felgen",
        "description_de": "Recycling Pneu PKW ohne Felgen",
        "description_fr": "Recyclage Pneu voiture sans jantes",
        "description_it": "Riciclaggio Pneumatici auto senza cerchi",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgRestabfälle",
        "description_de": "Recycling Restabfälle kg",
        "description_fr": "Recyclage des déchets résiduels kg",
        "description_it": "Riciclaggio dei rifiuti residui kg",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgSENS-Geräte",
        "description_de": "Recycling SENS-Geräte",
        "description_fr": "Recyclage des marchandises SENS",
        "description_it": "Riciclaggio di beni SENS",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgStromzähler",
        "description_de": "Recycling Stromzähler",
        "description_fr": "Recyclage compteurs d'électricité",
        "description_it": "Riciclaggio di contatori elettrici",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgSWICO",
        "description_de": "Recycling SWICO-Ware",
        "description_fr": "Recyclage des marchandises SWICO",
        "description_it": "Riciclaggio di beni SWICO",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgTrafokerne mit Cu Spule",
        "description_de": "Recycling Trafokerne mit Cu Spule",
        "description_fr": "noyaux de transformateurs avec bobine de Cu",
        "description_it": "nuclei di trasformatori con bobina di Cu",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgTransformatoren gross",
        "description_de": "Transformatoren gross",
        "description_fr": "Transformateurs grands",
        "description_it": "Trasformatori di grandi dimensioni",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgTrennware 1",
        "description_de": "Recycling Trennware 1",
        "description_fr": "Recyclage des matériaux de séparation 1",
        "description_it": "Separazione del materiale di riciclo 1",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rkgTrennware 2",
        "description_de": "Recycling Trennware 2",
        "description_fr": "Recyclage des matériaux de séparation 2",
        "description_it": "Separazione del materiale di riciclo 2",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "kg",
    },
    {
        "bz_art": "rLeerung",
        "description_de": "Leerung",
        "description_fr": "Vidange",
        "description_it": "Svuotamento",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "Stück",
    },
    {
        "bz_art": "RVArealNetz",
        "description_de": "Rückvergütung Arealnetz",
        "description_fr": "Remboursement réseau d'areal",
        "description_it": "Rimborso rete areale",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "SA_L",
        "description_de": "Steuern/Abg",
        "description_fr": "Taxes publiques",
        "description_it": "Contributi ai comuni",
        "price_unit": "CHF/kWh",
        "type": "Netznutzung",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "SA_Z",
        "description_de": "Steuern/Abgaben auf Strom Zeitbezogen",
        "description_fr": "Taxes publiques",
        "description_it": "Contributi ai comuni relativi al tempo",
        "price_unit": "CHF",
        "type": "Netznutzung",
        "unit_quantity": "",
    },
    {
        "bz_art": "SF_kWh",
        "description_de": "Service Fees Energie",
        "description_fr": "Taxe de service energie",
        "description_it": "Tariffa servizio energia",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Skonto",
        "description_de": "Skonto",
        "description_fr": "Escompte",
        "description_it": "Sconto",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "SpotEinkaufHT",
        "description_de": "Einkauf Spot Hochtarif",
        "description_fr": "Spot HP",
        "description_it": "Spot tariffa alta",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "SpotEinkaufNT",
        "description_de": "Einkauf Spot NT",
        "description_fr": "Spot HC",
        "description_it": "Spot tariffa bassa",
        "price_unit": "CHF/kWh",
        "type": "NULL",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Stromzertifikate",
        "description_de": "Zertifikate zur Verbesserung der Stromqualität",
        "description_fr": "Certif. pour l'amélioration de la qualité energie",
        "description_it": "Certificato per migliorameno qualita energia",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "TF",
        "description_de": "Tankfüllung",
        "description_fr": "Remplissage du réservoir",
        "description_it": "Pieno, serbatoio",
        "price_unit": "CHF/L",
        "type": "Energie",
        "unit_quantity": "",
    },
    {
        "bz_art": "Verguetung_Mob_Ergy",
        "description_de": "Vergütung",
        "description_fr": "Rémunération",
        "description_it": "Remunerazione",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
    {
        "bz_art": "Verz_ZS",
        "description_de": "Verzugszinsen",
        "description_fr": "Intérêt sur retard",
        "description_it": "Interesse di mora",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "Wasser",
        "description_de": "Wasser",
        "description_fr": "Eau",
        "description_it": "Acqua",
        "price_unit": "CHF/m³",
        "type": "Energie",
        "unit_quantity": "m³",
    },
    {
        "bz_art": "XA",
        "description_de": "Abwasser",
        "description_fr": "Épuration",
        "description_it": "Acqua di scarico",
        "price_unit": "CHF/m³",
        "type": "Energie",
        "unit_quantity": "m³",
    },
    {
        "bz_art": "XK",
        "description_de": "Kehrichtgebühren",
        "description_fr": "Déchets",
        "description_it": "Rifiuti",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "Stück",
    },
    {
        "bz_art": "XS",
        "description_de": "Splittinggebühr",
        "description_fr": "Frais de fractionnement",
        "description_it": "Spese splitting",
        "price_unit": "CHF",
        "type": "NULL",
        "unit_quantity": "",
    },
    {
        "bz_art": "ZEE",
        "description_de": "Zuschlag Energiequalität",
        "description_fr": "Supplément qualité d'énergie",
        "description_it": "Supplemento energia rinnovabile",
        "price_unit": "CHF/kWh",
        "type": "Energie",
        "unit_quantity": "kWh",
    },
]
